# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [5]:
print(np.__version__)
print(np.__config__.show())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SUDEV DAS P/anaconda3\\Library\\include

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
memory_size = arr.nbytes

print(memory_size)
    

20


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [10]:
    np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [11]:
zeros = np.zeros(10)
zeros[4]=1
print(zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [15]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [22]:
vec = np.array([1,2,3,4,5,6,7,8,9])
re_vec = vec[::-1]
print(re_vec)

[9 8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [25]:
X = np.arange(0,9)
X2D = X.reshape(3,3)
print(X2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [29]:
ar = np.array([1,2,0,0,4,0])
np.nonzero(ar)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [30]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [35]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)


[[[0.36243052 0.26872621 0.66341764]
  [0.74297504 0.39393174 0.08178036]
  [0.66982062 0.14286767 0.50009505]]

 [[0.05103585 0.77449143 0.12668535]
  [0.57093914 0.09411142 0.38428843]
  [0.58403228 0.10802828 0.67579264]]

 [[0.31788564 0.29585646 0.4124569 ]
  [0.73386659 0.25182455 0.21272967]
  [0.15287083 0.37500234 0.82449434]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [42]:
arr = np.random.random((10,10))
print(arr)
print(arr.min())
print(arr.max())

[[0.19647216 0.29778906 0.35721886 0.22001494 0.61822237 0.98152479
  0.29716007 0.26414723 0.40548759 0.35260674]
 [0.71350576 0.27317138 0.28972327 0.63752443 0.37243033 0.86238988
  0.42556226 0.03883386 0.60322335 0.37836856]
 [0.51504022 0.87716651 0.37840454 0.81227602 0.27818895 0.15994526
  0.75306897 0.48704481 0.76661114 0.46836462]
 [0.752415   0.85489094 0.48297696 0.14988774 0.41296999 0.9068437
  0.9658299  0.12764381 0.5754618  0.18487058]
 [0.58852515 0.247515   0.18177837 0.7541857  0.3191444  0.42550291
  0.73943811 0.05690489 0.48835112 0.22334456]
 [0.6108607  0.5854895  0.84361036 0.29784687 0.6554239  0.17099363
  0.68598873 0.97579423 0.99732866 0.10202748]
 [0.88821353 0.68981549 0.52076934 0.11984783 0.53145147 0.90289745
  0.1666146  0.70238399 0.45903914 0.81983416]
 [0.14557218 0.71659008 0.39619285 0.17868795 0.47688089 0.52825921
  0.89502437 0.27857189 0.03295984 0.91269698]
 [0.87732359 0.15735668 0.51577088 0.06539746 0.50831467 0.55736898
  0.99140405 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [45]:
arr = np.random.rand(30)
arr.mean()

0.530272017071068

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [48]:
zarr = np.zeros((5,5))
zarr[0,:]=1
zarr[-1,:]=1
zarr[:,0] = 1
zarr[:,-1]=1
print(zarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [57]:
import numpy as np
arr = np.random.random((3, 3))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)
print(arr)


[[1.         1.         1.         1.         1.        ]
 [1.         0.80048658 0.83902887 0.59231359 1.        ]
 [1.         0.93770881 0.86267168 0.10627289 1.        ]
 [1.         0.18653341 0.69899837 0.00493465 1.        ]
 [1.         1.         1.         1.         1.        ]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [62]:
nan
False
False
nan
False

nan False False nan False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [71]:
np.diag([1,2,3,4],-1) 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [72]:
import numpy as np
mat = np.zeros((8, 8), dtype=int)
mat[::2, ::2] = 1
mat[1::2, 1::2] = 1
print(mat)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [11]:
ar = np.random.rand(6,7,8)
print(ar)
ind = np.unravel_index(99,ar.shape)
print(ar[ind])
print(ind)

[[[0.06049034 0.74711695 0.03937334 0.03152509 0.50947065 0.95992514
   0.16200478 0.244356  ]
  [0.2519776  0.1965402  0.14863635 0.39457989 0.56349256 0.30059817
   0.15595807 0.98529885]
  [0.0093252  0.79301238 0.54312949 0.15816284 0.76012294 0.94014359
   0.8513477  0.05311321]
  [0.32938529 0.66799719 0.4418054  0.07034958 0.06305449 0.54332184
   0.50672765 0.04831329]
  [0.49463315 0.69122864 0.10577564 0.85644718 0.91739517 0.22681504
   0.65524915 0.68177167]
  [0.23159398 0.51562491 0.42848681 0.68997456 0.88586777 0.1628168
   0.09158271 0.80592425]
  [0.11993931 0.10698623 0.43904915 0.57599114 0.2815943  0.58383449
   0.1395597  0.91310705]]

 [[0.63658038 0.40452482 0.61079911 0.3834577  0.8263696  0.361702
   0.67681312 0.47423142]
  [0.46055702 0.19442626 0.81153996 0.89522163 0.65309673 0.62715625
   0.43110772 0.96569194]
  [0.92213515 0.07585417 0.24923471 0.92030079 0.98940545 0.90551022
   0.12927333 0.716058  ]
  [0.54239105 0.4177905  0.61759204 0.97905823 0.64

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [3]:
import numpy as np

checkerboard = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [4]:
import numpy as np
matrix = np.random.rand(5,5)
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print(normalized_matrix)

[[1.         0.87006806 0.53270715 0.74385186 0.99337841]
 [0.771347   0.85103755 0.85508733 0.0228567  0.6206609 ]
 [0.29748515 0.         0.74332531 0.60136788 0.9975942 ]
 [0.97770442 0.73600253 0.74776101 0.22275518 0.28552442]
 [0.06805722 0.7594525  0.46633803 0.6426488  0.66302931]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [5]:
import numpy as np
color_dtype = np.dtype([("r", np.uint8), ("g", np.uint8), ("b", np.uint8), ("a", np.uint8)])
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255)], dtype=color_dtype)
print(color_array)

[(255,   0, 0, 255) (  0, 255, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [17]:
m1 = np.random.randint(10, size = (5,3))
m2 = np.random.randint(10, size = (3,2))
m_prod = m1 @ m2
m_prod

array([[ 94, 115],
       [ 48,  51],
       [ 77, 132],
       [ 94, 137],
       [ 69,  74]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = np.where((3 <= arr) & (arr <= 8), -arr,arr)
print(arr)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
9
10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [8]:
divide by zero
divide by zero
array([-2.14748365e+09])

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [12]:
x = np.array([1.2345, 2.3456, 3.4567])
x_rounded = np.around(x, 2)
x_rounded


array([1.23, 2.35, 3.46])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [15]:
ar1 = np.array([4,5,6,9,5,2,5,6])
ar2 = np.array([4,7,2,56,8,4,534,9,5])
i_ar = np.intersect1d(ar1,ar2)
print(i_ar)

[2 4 5 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [16]:
np.seterr

<function numpy.seterr(all=None, divide=None, over=None, under=None, invalid=None)>

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [11]:
no

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [17]:
np.random.randint(2,size=10)

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [24]:
import numpy as np
x = np.random.rand(10)
x.sort()
print(x)

[0.00942194 0.18957729 0.36174353 0.39798412 0.43495186 0.4811991
 0.6086371  0.68955035 0.74349552 0.91015843]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)